# Welcome to TokenStream!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TokenStream | Digital Assets Trading Data Aggregator
email: info@tokenstream.co
description: > # this means to ignore newlines until "baseurl:"
  TokenStream operates at the heart of the token economy by aggregating and providing downloadable, real-time time digital assets trading data from all major token exchanges. A must have tool for any serious cryptoasset trader!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: #tokenstream
github_username:  tokenstream

# Build settings
markdown: kramdown
